"""empty message

Revision ID: 87b81fb78a44
Revises: 
Create Date: 2024-02-01 11:16:26.169016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87b81fb78a44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('propert_agent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent_img', sa.String(length=255), nullable=False))

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_img', sa.String(length=255), nullable=False))

    with op.batch_alter_table('testimonials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_img', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testimonials', schema=None) as batch_op:
        batch_op.drop_column('client_img')

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('property_img')

    with op.batch_alter_table('propert_agent', schema=None) as batch_op:
        batch_op.drop_column('agent_img')

    # ### end Alembic commands ###
